"""
convert_all_assets.py — Convert all badge assets for ESP32-S3-Touch-LCD-4 (480x480)

Features:
- Preserves aspect ratio (fit inside target box)
- Adds white background for transparent PNG (NI Logo 5, 7)
- Background image: resize fill to 480x480
- Avatar: circular crop 160x160 with alpha mask
"""
import sys
import os
import struct
from pathlib import Path
from PIL import Image

def rgb888_to_rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def write_c_array(data, output_path, var_name, w, h, cf):
    with open(output_path, 'w') as f:
        f.write(f'/* Auto-generated by convert_all_assets.py */\n')
        f.write(f'/* Size: {w}x{h}, Format: {cf} */\n\n')
        f.write('#include "lvgl.h"\n\n')
        f.write(f'static const uint8_t {var_name}_data[] = {{\n')
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
            f.write(f'    {hex_str},\n')
        f.write('};\n\n')
        f.write(f'const lv_img_dsc_t {var_name} = {{\n')
        f.write(f'    .header.always_zero = 0,\n')
        f.write(f'    .header.w = {w},\n')
        f.write(f'    .header.h = {h},\n')
        f.write(f'    .header.cf = {cf},\n')
        f.write(f'    .data_size = {len(data)},\n')
        f.write(f'    .data = {var_name}_data,\n')
        f.write('};\n')
    print(f"  OK: {var_name} ({w}x{h}, {len(data)} bytes, {cf})")

def convert_fill(input_path, output_path, target_w, target_h, var_name):
    """Resize to fill entire target area (may crop)."""
    img = Image.open(input_path).convert("RGB")
    img = img.resize((target_w, target_h), Image.LANCZOS)
    data = bytearray()
    for y in range(target_h):
        for x in range(target_w):
            r, g, b = img.getpixel((x, y))
            data += struct.pack('<H', rgb888_to_rgb565(r, g, b))
    write_c_array(data, output_path, var_name, target_w, target_h, "LV_IMG_CF_TRUE_COLOR")

def convert_avatar(input_path, output_path, size, var_name):
    """Square crop center, resize, apply circular alpha mask."""
    img = Image.open(input_path).convert("RGBA")
    # Center crop to square
    w, h = img.size
    s = min(w, h)
    left = (w - s) // 2
    top = (h - s) // 2
    img = img.crop((left, top, left + s, top + s))
    img = img.resize((size, size), Image.LANCZOS)
    # Apply circular mask
    from PIL import ImageDraw
    mask = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(mask)
    draw.ellipse((0, 0, size-1, size-1), fill=255)
    # Composite alpha
    r, g, b, a = img.split()
    a = Image.composite(a, Image.new("L", (size, size), 0), mask)
    img = Image.merge("RGBA", (r, g, b, a))
    # Encode as RGB565 + Alpha (LVGL TRUE_COLOR_ALPHA = color_lo, color_hi, alpha)
    data = bytearray()
    for y in range(size):
        for x in range(size):
            r, g, b, alpha = img.getpixel((x, y))
            rgb565 = rgb888_to_rgb565(r, g, b)
            data += struct.pack('<H', rgb565)
            data.append(alpha)
    write_c_array(data, output_path, var_name, size, size, "LV_IMG_CF_TRUE_COLOR_ALPHA")

def convert_fit(input_path, output_path, max_w, max_h, var_name, white_bg=False):
    """Resize to fit inside max_w x max_h box, preserving aspect ratio.
    If white_bg=True, fill background with white (for transparent PNGs).
    Output actual dimensions (not padded)."""
    img = Image.open(input_path).convert("RGBA")
    orig_w, orig_h = img.size
    # Calculate scale to fit
    scale = min(max_w / orig_w, max_h / orig_h)
    new_w = int(orig_w * scale)
    new_h = int(orig_h * scale)
    img = img.resize((new_w, new_h), Image.LANCZOS)
    
    has_alpha = any(px[3] < 255 for px in img.getdata())
    
    if white_bg or (has_alpha and white_bg):
        # Composite onto white background
        bg = Image.new("RGB", (new_w, new_h), (255, 255, 255))
        bg.paste(img, mask=img.split()[3])
        img = bg.convert("RGBA")
        has_alpha = False
    
    if has_alpha and not white_bg:
        # Keep alpha channel (LVGL: color_lo, color_hi, alpha)
        data = bytearray()
        for y in range(new_h):
            for x in range(new_w):
                r, g, b, a = img.getpixel((x, y))
                rgb565 = rgb888_to_rgb565(r, g, b)
                data += struct.pack('<H', rgb565)
                data.append(a)
        write_c_array(data, output_path, var_name, new_w, new_h, "LV_IMG_CF_TRUE_COLOR_ALPHA")
    else:
        # No alpha
        data = bytearray()
        for y in range(new_h):
            for x in range(new_w):
                px = img.getpixel((x, y))
                r, g, b = px[0], px[1], px[2]
                data += struct.pack('<H', rgb888_to_rgb565(r, g, b))
        write_c_array(data, output_path, var_name, new_w, new_h, "LV_IMG_CF_TRUE_COLOR")

def convert_logo_preserve_ratio(input_path, output_path, max_w, max_h, var_name):
    """For NI5040 logo: resize to fit, preserve aspect ratio, no alpha."""
    img = Image.open(input_path).convert("RGBA")
    orig_w, orig_h = img.size
    scale = min(max_w / orig_w, max_h / orig_h)
    new_w = int(orig_w * scale)
    new_h = int(orig_h * scale)
    img = img.resize((new_w, new_h), Image.LANCZOS)
    # Composite onto dark background (matches card page bg)
    bg = Image.new("RGBA", (new_w, new_h), (20, 27, 45, 0))
    bg.paste(img, mask=img.split()[3])
    # Output with alpha for transparency on dark bg (LVGL: color_lo, color_hi, alpha)
    data = bytearray()
    for y in range(new_h):
        for x in range(new_w):
            r, g, b, a = img.getpixel((x, y))
            rgb565 = rgb888_to_rgb565(r, g, b)
            data += struct.pack('<H', rgb565)
            data.append(a)
    write_c_array(data, output_path, var_name, new_w, new_h, "LV_IMG_CF_TRUE_COLOR_ALPHA")


if __name__ == '__main__':
    project_root = Path(__file__).resolve().parents[1]
    workspace_root = project_root.parents[4]
    SRC = str(workspace_root / "raw" / "esp32-badge" / "source-materials")
    DST = str(project_root / "main" / "assets")
    GAL = os.path.join(DST, "gallery")
    os.makedirs(GAL, exist_ok=True)

    print("=== Converting background pattern (480x480) ===")
    convert_fill(
        os.path.join(SRC, "NI50_Pattern_3A.png"),
        os.path.join(DST, "img_bg_pattern.c"),
        480, 480, "img_bg_pattern"
    )

    print("\n=== Converting avatar (160x160 circle with alpha) ===")
    convert_avatar(
        os.path.join(SRC, "头像.png"),
        os.path.join(DST, "img_avatar_160.c"),
        160, "img_avatar_160"
    )

    print("\n=== Converting NI5040 logo (preserve aspect ratio, max 248x139) ===")
    convert_logo_preserve_ratio(
        os.path.join(SRC, "NI5040.webp"),
        os.path.join(DST, "img_ni5040_logo.c"),
        248, 139, "img_ni5040_logo"
    )

    print("\n=== Converting WeChat QR code (fit 150x150) ===")
    convert_fit(
        os.path.join(SRC, "wechat.jpg"),
        os.path.join(DST, "img_wechat_qr.c"),
        150, 150, "img_wechat_qr"
    )

    print("\n=== Converting milestone images (fit in 400x146) ===")
    convert_fit(
        os.path.join(SRC, "1976.jpg"),
        os.path.join(GAL, "img_ms_1976.c"),
        400, 146, "img_ms_1976"
    )
    lv1_dir = os.path.join(SRC, "LabVIEW 1.0")
    convert_fit(
        os.path.join(lv1_dir, "LV1SplashScreen.jpg"),
        os.path.join(GAL, "img_ms_1986.c"),
        400, 146, "img_ms_1986"
    )
    convert_fit(
        os.path.join(SRC, "NIWeek95.png"),
        os.path.join(GAL, "img_ms_1995.c"),
        400, 146, "img_ms_1995"
    )
    convert_fit(
        os.path.join(SRC, "PXI-1000.jpg"),
        os.path.join(GAL, "img_ms_1997.c"),
        400, 146, "img_ms_1997"
    )
    convert_fit(
        os.path.join(SRC, "cRIO.jpg"),
        os.path.join(GAL, "img_ms_2004.c"),
        400, 146, "img_ms_2004"
    )
    convert_fit(
        os.path.join(SRC, "EMR 2023.png"),
        os.path.join(GAL, "img_ms_2023.c"),
        400, 146, "img_ms_2023"
    )
    convert_fit(
        os.path.join(SRC, "NI5040.webp"),
        os.path.join(GAL, "img_ms_2026.c"),
        400, 146, "img_ms_2026",
        white_bg=True
    )

    print("\n=== Converting LabVIEW 1.0 gallery (fit in 400x300, preserve ratio) ===")
    lv1_dir = os.path.join(SRC, "LabVIEW 1.0")
    convert_fit(
        os.path.join(lv1_dir, "LV1BlockDiagram.jpg"),
        os.path.join(GAL, "img_lv1_block.c"),
        400, 300, "img_lv1_block"
    )
    convert_fit(
        os.path.join(lv1_dir, "LV1SplashScreen.jpg"),
        os.path.join(GAL, "img_lv1_splash.c"),
        400, 300, "img_lv1_splash"
    )
    convert_fit(
        os.path.join(lv1_dir, "news.png"),
        os.path.join(GAL, "img_lv1_news.c"),
        400, 300, "img_lv1_news"
    )

    print("\n=== All conversions complete ===")
