"""
img2lvgl.py — Convert images to LVGL 8.x C array (RGB565, little-endian)
Usage: python img2lvgl.py <input_image> <output_c_file> <width> <height> [var_name]
"""
import sys
from PIL import Image
import struct
import os

def rgb888_to_rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def convert(input_path, output_path, target_w, target_h, var_name=None):
    img = Image.open(input_path).convert("RGBA")
    img = img.resize((target_w, target_h), Image.LANCZOS)
    
    if var_name is None:
        var_name = os.path.splitext(os.path.basename(output_path))[0]
    
    has_alpha = any(px[3] < 255 for px in img.getdata())
    
    if has_alpha:
        # ARGB8565 format: 1 byte alpha + 2 bytes RGB565
        cf = "LV_IMG_CF_TRUE_COLOR_ALPHA"
        bpp = 3
        data = bytearray()
        for y in range(target_h):
            for x in range(target_w):
                r, g, b, a = img.getpixel((x, y))
                rgb565 = rgb888_to_rgb565(r, g, b)
                data.append(a)
                data += struct.pack('<H', rgb565)
    else:
        # RGB565 format
        cf = "LV_IMG_CF_TRUE_COLOR"
        bpp = 2
        data = bytearray()
        for y in range(target_h):
            for x in range(target_w):
                r, g, b, _ = img.getpixel((x, y))
                rgb565 = rgb888_to_rgb565(r, g, b)
                data += struct.pack('<H', rgb565)
    
    # Write C file
    with open(output_path, 'w') as f:
        f.write(f'/* Auto-generated by img2lvgl.py from {os.path.basename(input_path)} */\n')
        f.write(f'/* Size: {target_w}x{target_h}, Format: {cf} */\n\n')
        f.write('#include "lvgl.h"\n\n')
        f.write(f'static const uint8_t {var_name}_data[] = {{\n')
        
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
            f.write(f'    {hex_str},\n')
        
        f.write('};\n\n')
        f.write(f'const lv_img_dsc_t {var_name} = {{\n')
        f.write(f'    .header.always_zero = 0,\n')
        f.write(f'    .header.w = {target_w},\n')
        f.write(f'    .header.h = {target_h},\n')
        f.write(f'    .header.cf = {cf},\n')
        f.write(f'    .data_size = {len(data)},\n')
        f.write(f'    .data = {var_name}_data,\n')
        f.write('};\n')
    
    print(f"OK: {input_path} -> {output_path} ({target_w}x{target_h}, {len(data)} bytes, {cf})")

if __name__ == '__main__':
    if len(sys.argv) < 5:
        print("Usage: python img2lvgl.py <input> <output.c> <width> <height> [var_name]")
        sys.exit(1)
    
    inp = sys.argv[1]
    out = sys.argv[2]
    w = int(sys.argv[3])
    h = int(sys.argv[4])
    name = sys.argv[5] if len(sys.argv) > 5 else None
    convert(inp, out, w, h, name)
